// <auto-generated />
namespace CloudBasedFingerIdentificationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class firstmg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmg));
        
        string IMigrationMetadata.Id
        {
            get { return "202205121326467_first mg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
